### ISSUE TITLE
Not enough description on integrals

### ISSUE THREAD

**Issue by RileyPaddock** [eoriont/assignment-projects#1]
This is a super minor thing but I feel that some of the integrals jump a couple steps. It would be a lot easier to understand if you at least got each integral to the step where it is just computation that would make it easier to fix. Honestly your code is really good and this was just something super minor I had to put because there was nothing else.

**Comment by eoriont** [comment]
With the integrals, I am using this format:
`Int(x) from 0 -> infinity`
For me, it's a nice text form, but I can see how it can be confusing. In a couple of my past assignments, I went over them and redid some problems that were wrong, and I will add more explanation in the future.
